const mongoose = require("mongoose");

const biodataSchema = new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    personal:{
        fullName:{
            type:String,
            required:true
        },
        profilePhoto:{
            type:String
        },
        gender:{
            type:String,
            required:true
        },
        dob:{
            type:Date,
            required:true
        },
        age:{
            type:Number
        },
        height:{
            type:String,
            required:true
        },
        religion:{
            type:String,
            required:true
        },
        caste:{
            type:String
        },
        motherTongue:{
            type:String
        },
        maritalStatus:{
            type:String,
            required:true
        },
        nationality:{
            type:String
        }
    },
    education:{
        educationDetails:{
            type:String,
            required:true
        },
        professionDetails:{
            type:String,
            required:true
        },
        annualIncome:{
            type:String
        }
    },
    family:{
        fatherName:{
            type:String,
            required:true
        },
        fatherOccupation:{
            type:String
        },
        motherName:{
            type:String,
            required:true
        },
        motherOccupation:{
            type:String
        },
        siblings:{
            type:String
        },
        familyType:{
            type:String
        },
        familyStatus:{
            type:String
        },
        nativePlace:{
            type:String
        }
    },
    horoscope:{
        rashi:{
            type:String
        },
        nakshatra:{
            type:String
        },
        gothra:{
            type:String
        },
        timeOfBirth:{
            type:String
        },
        placeOfBirth:{
            type:String
        }
    },
    contact:{
        phone:{
            type:String,
            required:true
        },
        email:{
            type:String
        },
        residentialAddress:{
            type:String
        },
        hideContactInfo:{
            type:Boolean,
            default: false
        }
    }
}, { timestamps: true })

module.exports = mongoose.model("Biodata",biodataSchema);